// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
eagerLoadControllersFrom("controllers", application)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import NotificationsController from "controllers/notifications_controller"
application.register("notifications", NotificationsController)