default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gestao_boletos_kobana_development

test:
  <<: *default
  database: gestao_boletos_kobana_test

production:
  <<: *default
  database: gestao_boletos_kobana_production
  username: gestao_boletos_kobana
  password: <%= ENV["GESTAO_BOLETOS_KOBANA_DATABASE_PASSWORD"] %>
